$folder = Join-Path $PSScriptRoot "probability-statistics"
$master = Join-Path $folder "probability-statistics.qmd"

$watcher = [System.IO.FileSystemWatcher]::new($folder, "_*.qmd")
$watcher.NotifyFilter = `
    [System.IO.NotifyFilters]::LastWrite -bor `
    [System.IO.NotifyFilters]::Size

$watcher.EnableRaisingEvents = $true

$lastTrigger = [DateTime]::MinValue

Write-Host "Watching included QMD files..."
Write-Host "Press Ctrl+C to stop."

try {

    while ($true) {

        $change = $watcher.WaitForChanged(
            [System.IO.WatcherChangeTypes]::Changed,
            1000
        )

        if ($change.TimedOut) {
            continue
        }

        $now = Get-Date

        # Avoid duplicate events generated by one save
        if (($now - $lastTrigger).TotalMilliseconds -lt 600) {
            continue
        }

        $lastTrigger = $now

        $text = [System.IO.File]::ReadAllText($master)

        $stamp = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()

        $newText = $text -replace `
            '<!-- preview-trigger: .*? -->',
            "<!-- preview-trigger: $stamp -->"

        [System.IO.File]::WriteAllText(
            $master,
            $newText,
            [System.Text.UTF8Encoding]::new($false)
        )

        Write-Host "Changed: $($change.Name) -> triggered probability-statistics.qmd"
    }
}
finally {
    $watcher.Dispose()
}